apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ci-cd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-ci-cd
  template:
    metadata:
      labels:
        app: test-ci-cd
    spec:
      containers:
      - name: test-ci-cd
        image: krobus00/test-ci-cd:v0.1.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
