name: go-build

on:
  workflow_dispatch:
     inputs:
      branch:
        description: 'branch to deploy'
        required: true
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file:       'go.mod'
          check-latest:          true
          cache-dependency-path: 'go.sum'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
