name: Deploy

on:
  push:
    branches:
      - 'fast-deployment/*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Application
      run: |
        echo "Deploying application..."
        echo "THIS IS MY CHANGES..."
        # Add deployment commands

    - name: Delete Deployment Branch
      run: |
        branch_name=${GITHUB_REF#refs/heads/}
        echo "Deleting branch $branch_name"
        git push origin --delete $branch_name
